### ISSUE TITLE
no module named 'parse'

### ISSUE THREAD

**Issue by kyleboddy** [PlantandFoodResearch/machine-vision-acquisition#10]
Error when running `docker compose up -d aravis multi-sdk` regarding the parse library.

```
27.47 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
27.61 Traceback (most recent call last):
27.61   File "<stdin>", line 27, in <module>
27.61 ModuleNotFoundError: No module named 'parse'
------
failed to solve: process "/bin/sh -c python3 -m pip install -U pip setuptools wheel     && python3 -m pip install -U PyGObject pycairo PyGObject-stubs     && apt-get install --yes libva-drm2 libpangoft2-1.0-0 libxvidcore4 libxkbcommon0 libchromaprint1 libpgm-5.3-0 libopus0 libwayland-cursor0 libpango-1.0-0 libbluray2 libsnappy1v5 libxrandr2 libthai0 libzvbi0 libnorm1 libpixman-1-0 libzmq5 libx265-192 libgraphite2-3 libxdamage1 libwayland-client0 libgtk-3-0 libsrt1.4-gnutls libxcursor1 libx264-160 libspeex1 libswscale5 libdav1d4 libmp3lame0 libgsm1 libatspi2.0-0 libxcb-render0 libavformat58 libvdpau1 libgme0 libcodec2-0.9 libwebpmux3 libshine3 libvorbis0a libsoxr0 libdrm2 libva-x11-2 libcairo-gobject2 libavutil56 libxfixes3 libvorbisfile3 librabbitmq4 libxrender1 libsodium23 libharfbuzz0b libtwolame0 libswresample3 libavcodec58 libxcomposite1 libwavpack1 libogg0 libepoxy0 libvorbisenc2 libxi6 libatlas3-base libgfortran5 libvpx6 libcairo2 libudfread0 libatk1.0-0 libgdk-pixbuf-2.0-0 libdatrie1 libmpg123-0 libxinerama1 libopenjp2-7 libaom0 libva2 libopenmpt0 libpangocairo-1.0-0 libwayland-egl1 libatk-bridge2.0-0 libtheora0 ocl-icd-libopencl1 libxcb-shm0 librsvg2-2 libssh-gcrypt-4 libgfortran5 libatlas3-base     && apt-get clean autoclean     && python3 -m pip install -U --only-binary=:all: numpy opencv-python     && mkdir -p /usr/lib/girepository-1.0/     && ln -s $(find /usr/local/lib/ -type f -name \"Aravis-0.8.typelib\") /usr/lib/girepository-1.0/     && wget -qO - https://raw.githubusercontent.com/pygobject/pygobject-stubs/master/tools/generate.py |     python3 - Aravis 0.8 >> $(python3 -c 'import site; print(site.getsitepackages()[0])')/gi-stubs/repository/Aravis.pyi" did not complete successfully: exit code: 1
```

Attempting to repair the dockerfiles manually to add `parse` into the pip install line then comes up with:

```
32.45 Installing collected packages: numpy, opencv-python
34.18 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
34.18 Successfully installed numpy-1.26.4 opencv-python-4.9.0.80
34.45 Traceback (most recent call last):
34.45   File "<stdin>", line 956, in <module>
34.45   File "<stdin>", line 930, in start
34.45   File "<stdin>", line 337, in _build
34.45   File "<stdin>", line 751, in _gi_build_stub
34.45   File "/usr/local/lib/python3.9/dist-packages/gi/module.py", line 130, in __getattr__
34.45     raise AttributeError("%r object has no attribute %r" % (
34.45 AttributeError: 'gi.repository.GIRepository' object has no attribute 'property_info_get_getter'
```

**Comment by mtbmartin** [comment]
Archiving repo
